# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: accident-predictor-service
spec:
  type: NodePort
  selector:
    app: accident-predictor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
