apiVersion: v1
kind: Service
metadata:
  name: traffic-accident-service
spec:
  type: NodePort   # LoadBalancer 쓰면 과금될 수 있으니 NodePort
  selector:
    app: traffic-accident
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007   # 클러스터 외부에서 접속할 포트
